title: Hello, world! I'm Sara Mc Carthy!
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
#baseurl: "./" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Sara Mc Carthy # add your name
author-img: sara.png # add your photo
about-author: PhD Researchare and Graduate from the University of Southern California # add description
about-author2: Artificial Intelligence, Game Theory, Optimization, Multi-Agent Systems and Machine Learning


github: saramccarthy # add your Github handle
linkedin: www.linkedin.com/in/sara-marie-mccarthy # add your Linkedin handle
email: sara.m.mccarthy@gmail.com # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 12
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
